FROM python:3.10-slim

# 避免 Python 缓存 & 强制 stdout 直出
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 安装系统级依赖（针对你的依赖树）
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    ca-certificates \
    libgl1 \
    libglib2.0-0 \
    libstdc++6 \
    libgomp1 \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 先拷贝 lock 文件，利用 Docker layer cache
COPY requirements.lock.txt .

RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.lock.txt

# 再拷贝你的项目代码
COPY . .


CMD ["python", "app.py"]
