embedding:
  local:
    cache_dir: null
    device: cpu
    model_name: paraphrase-multilingual-MiniLM-L12-v2
  mode: remote
  remote:
    api_endpoint: https://api-inference.modelscope.cn/v1
    api_key: ms-94340098-d1cf-4237-ba1f-fa8333b6e97f
    max_retries: 3
    model_name: Qwen/Qwen3-Embedding-8B
    timeout: 30
external_libs:
  json2graph: {}
  llmjson: {}
llm:
  api_endpoint: https://api.deepseek.com/v1
  api_key: ''
  max_tokens: 4608
  model_name: deepseek-chat
  provider: test2
  retry_attempts: 3
  temperature: 0.7
  timeout: 30
neo4j:
  password: admin123456
  uri: bolt://localhost:7687
  user: neo4j
system:
  max_content_length: 104857600
